### ISSUE TITLE
JavaScript Wikipedia API

### ISSUE THREAD

**Issue by AmeliaBigler** [AmeliaBigler/volunear#10]
# JavaScript Wikipedia API
## User Story
As a volunteer,
I want an app that shows me non-profit organizations near me based on my interests,
so that I can learn about opportunities to get involved and volunteer.

## Acceptance Criteria
GIVEN an app with input fields for my location and interests,
WHEN I view the results for a search,
THEN I see a list of non-profit organizations and Wikipedia information about each one.

**Comment by kitrath** [comment]
After researching Wikipedia's API (which is extensive, and would be super-helpful if you were building a bot to take actions on Wikipedia), it seems like a dead-end for our project.

**Comment by AmeliaBigler** [comment]
Great! Thank you for looking in to that. We can edit this issue to reflect the new direction we decide to take.

**Comment by kitrath** [comment]
OK.  I'm going to go ahead and close this issue.
